Repository conceptsandtraining/doil, pull requests merged in 2022-11, with the labels that each got.

#238 master states/templates: 237 nginx now starts with supervisor
  app/src/Commands/Salt/RestartCommand.php
  app/src/Commands/Salt/UpCommand.php
  app/tests/Commands/Salt/RestartCommandTest.php
  app/tests/Commands/Salt/UpCommandTest.php
  setup/stack/states/proxyservices/proxyservices/sv-nginx.conf
  setup/templates/proxy/conf/salt-startup.sh
  setup/templates/proxy/conf/startup.conf
Labels: bug

#239 master readme: 236 adjust old doil commands
  README.md
Labels: improvement

#243 Minor wording change...
  app/src/Commands/Instances/CreateCommand.php
Labels: improvement

#245 master install: 235 add port check
  setup/checks.sh
  setup/install.sh
Labels: improvement

#244 master install: 234 add requirement check if user is in doil group
  setup/checks.sh
  setup/install.sh
  setup/system.sh
Labels: improvement

#246 master install: 240 allow composer to run as super user
  setup/system.sh
Labels: bug

#247 master readme: 241 make it clear wich parameter is for name and which for branch
  README.md
Labels: documentation, improvement

#252 feature_release commands:210 add new command 'exec'
  README.md
  app/src/Commands/Instances/ExecCommand.php
  app/src/Lib/Docker/Docker.php
  app/src/Lib/Docker/DockerShell.php
  app/src/cli.php
Labels: improvement
