Repository conceptsandtraining/doil, pull requests merged in 2023-02, with the labels that each got.

#284 feature_release pack:281 adjust regex for instance names
  app/src/Commands/Pack/ExportCommand.php
  app/src/Commands/Pack/ImportCommand.php
Labels: bug, review

#285 feature_release pack:282 implement confirmation before overwriting a file
  app/src/Commands/Pack/ExportCommand.php
Labels: improvement, review

#289 feature_release user:288 implement acknowledgement confirmation
  app/src/Commands/User/DeleteCommand.php
  app/tests/Commands/User/DeleteCommandTest.php
Labels: improvement, review

#290 Feature release: Small fix for a very unlikely error message during update
  setup/helper.sh
Labels: bug

#291 feature_release state/ilias_postinstall:287 add property 'ignore_if_missing' for ilias without auotinstaller
  setup/stack/states/ilias-postinstall/devmode/init.sls
Labels: bug

#297 mv apt-update in same row as apt-get install, ajust composer call
  app/src/App.php
  app/src/Commands/Instances/CreateCommand.php
  setup/system.sh
  setup/templates/minion/Dockerfile
  setup/updates/update-20230223.sh
  setup/updates/update.sh
Labels: bug
